### PR TITLE
Implement search function for HashLinkedListSequential

### PR DESCRIPTION
**Pull request by Jessica7chen**

### CODE REVIEW

**Review by Andision — CHANGES_REQUESTED** [review]
Why add a new function `search` instead of modifying the `find` function

**Comment by Jessica7chen** [comment]
updated

**Review by Andision — CHANGES_REQUESTED** [review]
Do NOT modify the declaration, which is defined in the `HashLinkedListSequential.h` file. This will cause declared but not implemented function.

**Comment by Jessica7chen** [comment]
Updated again, please check.

**Review by yingzisun123 — APPROVED** [review]

**Review by Andision — APPROVED** [review]
cool!

**Pull request merged**
